[package]
name = "zmod-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
swc_core.workspace = true
serde.workspace = true
serde_json.workspace = true
